[mgr]
cwd = {{ fg = "{primary}" }}

hovered         = {{ reversed = true }}
preview_hovered = {{ underline = true }}

find_keyword  = {{ fg = "red", bold = true, italic = true, underline = true }}
find_position = {{ bg = "reset", bold = true, italic = true }}

marker_copied   = {{ fg = "{secondary}",  bg = "{secondary}" }}
marker_cut      = {{ fg = "{warning}",    bg = "{warning}" }}
marker_marked   = {{ fg = "{primary}",   bg = "{primary}" }}
marker_selected = {{ fg = "{primary}", bg = "{primary}" }}

tab_active   = {{ reversed = true }}
tab_inactive = {{}}
tab_width    = 1

count_copied   = {{ fg = "{foreground_base}", bg = "green" }}
count_cut      = {{ fg = "{foreground_base}", bg = "red" }}
count_selected = {{ fg = "{foreground_base}", bg = "yellow" }}

border_symbol = "│"
border_style  = {{ fg = "{foreground_faded}" }}

[status]
sep_left = {{ open = "", close = "»" }}
sep_right = {{ open = "«", close = "" }}

[mode]
normal_main = {{ fg = "{primary}", bg = "reset", bold = true }}
normal_alt  = {{ fg = "{primary}", bg = "reset" }}
select_main = {{ fg = "red", bg = "reset", bold = true }}
select_alt  = {{ fg = "red", bg = "reset" }}
unset_main = {{ fg = "red", bg = "reset", bold = true }}
unset_alt  = {{ fg = "red", bg = "reset" }}

perm_sep   = {{ fg = "darkgray" }}
perm_type  = {{ fg = "green" }}
perm_read  = {{ fg = "yellow" }}
perm_write = {{ fg = "red" }}
perm_exec  = {{ fg = "cyan" }}

progress_label  = {{ bold = true }}
progress_normal = {{ fg = "{primary}", bg = "{background_base}" }}
progress_error  = {{ fg = "red", bg = "{background_base}" }}

[which]
cols            = 3
mask            = {{ bg = "{background_base}" }}
cand            = {{ fg = "lightcyan" }}
rest            = {{ fg = "darkgray" }}
desc            = {{ fg = "lightmagenta" }}
separator       = "  "
separator_style = {{ fg = "darkgray" }}

[confirm]
border     = {{ fg = "{primary}" }}
title      = {{ fg = "{primary}" }}
content    = {{}}
list       = {{}}
btn_yes    = {{ reversed = true }}
btn_no     = {{}}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border = {{ fg = "{primary}" }}
title  = {{ fg = "{primary}" }}

[notify]
title_info  = {{ fg = "{primary}" }}
title_warn  = {{ fg = "yellow" }}
title_error = {{ fg = "red" }}

[pick]
border   = {{ fg = "{primary}" }}
active   = {{ fg = "magenta", bold = true }}
inactive = {{}}

[input]
border   = {{ fg = "{primary}" }}
title    = {{}}
value    = {{}}
selected = {{ reversed = true }}

[completion]
border   = {{ fg = "{primary}" }}
active   = {{ reversed = true }}
inactive = {{}}

[tasks]
border  = {{ fg = "{primary}" }}
title   = {{}}
hovered = {{ fg = "magenta", underline = true }}

[tabs]
active = {{ fg = "{on_primary}", bg = "{primary}" }}
inactive = {{ fg = "{foreground_base}", bg = "{background_view}" }}
sep_inner = {{ open = "", close = "" }}
sep_outer = {{ open = "", close = "" }}

[help]
on      = {{ fg = "{primary}", bold = true }}
run     = {{ fg = "{primary}", italic = true }}
desc    = {{}}
hovered = {{ reversed = true }}
footer  = {{ fg = "{background_base}", bg = "{foreground_base}" }}

[filetype]
rules = [
	# Special files
	{{ name = "*", fg = "{foreground_base}" }},
    {{ name = "*", is = "link", italic = true }},
	{{ name = "*", is = "orphan", bg = "red" }},
	{{ name = "*", is = "exec"  , fg = "{warning_name}" }},
	{{ name = "*/", fg = "{primary}" }}
]

